version: '3.1'

services:

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dsmovies
      POSTGRES_PASSWORD: 1234567

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
